# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

import sphinx_rtd_theme

# -- Project information -----------------------------------------------------

project = '多因子回测框架'
title = '多因子回测框架文档'
copyright = '2020, 融量'
author = '融量'

master_doc = 'index'

# The full version, including alpha/beta/rc tags
version = '0.1.0'
release = version
numfig = True

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.

extensions = [
    "sphinx_rtd_theme",
    "docxbuilder"
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_CN'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"
html_show_sourcelink = False

html_theme_options = {
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    # 'style_nav_header_background': 'blue',
    # Toc options
    'collapse_navigation': True,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


# -- Options for latex output ----------------------------------------------

latex_engine = "xelatex"

latex_elements = {
    "papersize": "a4paper",
    'fncychap': "\\usepackage[Sonny]{fncychap}",
    'inputenc': "",
    'utf8extra': "",
    'fontpkg': '\\usepackage{amsmath,amsfonts,amssymb,amsthm}',
    'preamble': r"""
    \setcounter{secnumdepth}{2}
    \setcounter{tocdepth}{2}
    \usepackage{fontspec}
    """,
    "figure_align": "H"
}

latex_documents = [
    ("index", 'main.tex', '多因子回测框架文档',
     '融量量化团队', 'manual')
]


# -- Options for docx output -----------------------------------------------
docx_documents = [
    ('index', 'quantitative_research.docx', {
         'title': '标准化模型服务文档',
         'created': '融量量化团队',
         'subject': '融量量化团队',
         'keywords': ['sphinx']
     }, True),
]

docx_style = "docx/style.docx"
docx_pagebreak_before_section = 1
