/* src/Common/config_ipopt.h.  Generated by configure.  */
/* src/Common/config_ipopt.h.in. */

#ifndef __CONFIG_IPOPT_H__
#define __CONFIG_IPOPT_H__

/* Version number of project */
#define IPOPT_VERSION "trunk"

/* Major Version number of project */
#define IPOPT_VERSION_MAJOR 9999

/* Minor Version number of project */
#define IPOPT_VERSION_MINOR 9999

/* Release Version number of project */
#define IPOPT_VERSION_RELEASE 9999

/* Define to the C type corresponding to Fortran INTEGER */
#define FORTRAN_INTEGER_TYPE int

#endif
