# -*- coding: utf-8 -*-
"""
Created on 2017-5-15

@author: cheng.li
"""

risk_factors_500 = ['CommunicationsAndTransportation',
                    'LeisureServices',
                    'MultiMedia',
                    'PublicUtility',
                    'Agriculture',
                    'ChemicalIndustry',
                    'MedicationAndBio',
                    'CommercialTrade',
                    'DefenseIndustry',
                    'HouseholdAppliances',
                    'ConstructionAndMaterial',
                    'BuildingDecoration',
                    'RealEstate',
                    'DiversifiedMetal',
                    'Machinary',
                    'MotorVehicle',
                    'ElectronicIndustry',
                    'ElectricalEquip',
                    'TextileAndGarment',
                    'Synthetics',
                    'Computer',
                    'LightManufacturing',
                    'Telecoms',
                    'ExtractiveIndustry',
                    'Metal',
                    'FoodAndBeverage',
                    'Size']


risk_factors_300 = ['CommunicationsAndTransportation',
                    'LeisureServices',
                    'MultiMedia',
                    'PublicUtility',
                    'Agriculture',
                    'ChemicalIndustry',
                    'MedicationAndBio',
                    'CommercialTrade',
                    'DefenseIndustry',
                    'HouseholdAppliances',
                    'ConstructionAndMaterial',
                    'BuildingDecoration',
                    'RealEstate',
                    'DiversifiedMetal',
                    'Machinary',
                    'MotorVehicle',
                    'ElectronicIndustry',
                    'ElectricalEquip',
                    'TextileAndGarment',
                    'Synthetics',
                    'Computer',
                    'Telecoms',
                    'ExtractiveIndustry',
                    'Metal',
                    'FoodAndBeverage',
                    'Size']
